# Generated by Django 2.1.1 on 2018-10-22 04:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('makeplan', '0002_auto_20181021_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=100),
        ),
    ]
