# Generated by Django 2.1.1 on 2018-10-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewfolder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='username',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AlterField(
            model_name='folder',
            name='filename',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
