# Generated by Django 2.1.1 on 2018-10-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewfolder', '0002_auto_20181014_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='filename',
            field=models.CharField(default='NULL', max_length=1000),
        ),
        migrations.AlterField(
            model_name='folder',
            name='filepath',
            field=models.CharField(default='NULL', max_length=400),
        ),
    ]
