# Generated by Django 2.1.1 on 2018-10-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinfo',
            name='chinesename',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='email',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='grade',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='hometown',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='phonenumber',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='researchtopic',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
